{{- $root := . }}
{{- $name := .Release.Name }}
{{- $namespace := .Release.Namespace }}
{{- $gracefullyPaused := default false (and .Values.global .Values.global.gracefullyPaused) }}
{{- with .Values.git }}
{{- range $j, $d := . }}
{{- if $d.toRepo.name -}}
apiVersion: git.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ $name }}-repo-{{ $j }}
  labels:
    {{- include "github-scaffolding.labels" $root | nindent 4 }}
  annotations:
    krateo.io/paused: "{{ $gracefullyPaused }}"
spec:
  unsupportedCapabilities: {{ $d.unsupportedCapabilities }}
  insecure: {{ $d.insecure }}
  configMapKeyRef:
    namespace: {{ $namespace }}
    name: {{ $name }}-replace-values
    key: values
  fromRepo:
    url: {{ include "github-scaffolding.fromRepoUrl" $d }}
    branch: {{ $d.fromRepo.branch }}
    authMethod: {{ $d.fromRepo.credentials.authMethod }}
    path: {{ $d.fromRepo.path }}
    secretRef:
      namespace: {{ $d.fromRepo.credentials.secretRef.namespace }}
      name: {{ $d.fromRepo.credentials.secretRef.name }}
      key: {{ $d.fromRepo.credentials.secretRef.key }}
  toRepo:
    url: {{ include "github-scaffolding.toRepoUrl" $d }}
    branch: {{ $d.toRepo.branch }}
    authMethod: {{ $d.toRepo.credentials.authMethod }}
    path: {{ $d.toRepo.path }}
    secretRef:
      namespace: {{ $d.toRepo.credentials.secretRef.namespace }}
      name: {{ $d.toRepo.credentials.secretRef.name }}
      key: {{ $d.toRepo.credentials.secretRef.key }}
---
{{- end }}
{{- end }}
{{- end }}