{{- $root := . }}
{{- $name := .Release.Name }}
{{- $gracefullyPaused := default false (and .Values.global .Values.global.gracefullyPaused) }}
{{- with .Values.git }}
{{- range $j, $d := . }}
{{- if $d.toRepo.name -}}
apiVersion: github.ogen.krateo.io/v1alpha1
kind: Repo
metadata:
  name: {{ $name }}-repo-{{ $d.toRepo.name }}
  labels:
    {{- include "github-scaffolding.labels" $root | nindent 4 }}
  annotations:
    krateo.io/connector-verbose: "{{ $d.toRepo.verbose }}"
    krateo.io/deletion-policy: {{ $d.toRepo.deletionPolicy | lower }}
    krateo.io/paused: "{{ $gracefullyPaused }}"
spec:
  configurationRef:
    name: {{ $d.toRepo.configurationRef.name }}
    namespace: {{ $d.toRepo.configurationRef.namespace }}
  org: {{ $d.toRepo.org }}
  name: {{ $d.toRepo.name }}
  private: {{ $d.toRepo.private }}
  auto_init: {{ $d.toRepo.initialize }}
---
{{- end }}
{{- end }}
{{- end }}